import type { ProductSpotlightPreset, SpotlightParams } from './product-spotlight.types'

/**
 * Each preset is a complete lighting rig. They are a finite, typed set for the
 * same reason variants are: callers pick an intent, the component owns the
 * numbers.
 */
export const SPOTLIGHT_PRESETS: Record<ProductSpotlightPreset, SpotlightParams> =
  {
    default: {
      lightHeight: 1.45,
      shadowStrength: 1,
      shadowSoftness: 0.044,
      minBrightness: 0.2,
      normalStrength: 1.5,
      parallax: 0,
      aoStrength: 0.3,
      shadowLength: 1.7,
      lightBoost: 0.6,
      highlight: 2.55,
      spotRadius: 0.31,
      spotFloor: 0.14,
      spotFalloff: 1,
      spotColor: '#ffffff',
      trackingSpeed: 50,
      returnSpeed: 350,
      fadeIn: 60,
      fadeOut: 200,
      hoverDelay: 150,
    },
    dramatic: {
      lightHeight: 0.8,
      shadowStrength: 1,
      shadowSoftness: 0.02,
      minBrightness: 0.05,
      normalStrength: 2.5,
      parallax: 0.025,
      aoStrength: 1.2,
      shadowLength: 2.5,
      lightBoost: 1.5,
      highlight: 3.5,
      spotRadius: 0.2,
      spotFloor: 0.04,
      spotFalloff: 1.8,
      spotColor: '#ffffff',
      trackingSpeed: 30,
      returnSpeed: 500,
      fadeIn: 40,
      fadeOut: 300,
      hoverDelay: 100,
    },
    soft: {
      lightHeight: 2.5,
      shadowStrength: 0.4,
      shadowSoftness: 0.12,
      minBrightness: 0.5,
      normalStrength: 0.8,
      parallax: 0,
      aoStrength: 0.1,
      shadowLength: 1,
      lightBoost: 0.4,
      highlight: 1.8,
      spotRadius: 0.8,
      spotFloor: 0.3,
      spotFalloff: 0.5,
      spotColor: '#ffffff',
      trackingSpeed: 80,
      returnSpeed: 600,
      fadeIn: 100,
      fadeOut: 400,
      hoverDelay: 200,
    },
    cinematic: {
      lightHeight: 1,
      shadowStrength: 0.85,
      shadowSoftness: 0.06,
      minBrightness: 0.15,
      normalStrength: 2,
      parallax: 0.04,
      aoStrength: 0.6,
      shadowLength: 2,
      lightBoost: 0.8,
      highlight: 2.8,
      spotRadius: 0.35,
      spotFloor: 0.1,
      spotFalloff: 1.3,
      spotColor: '#ffffff',
      trackingSpeed: 40,
      returnSpeed: 450,
      fadeIn: 50,
      fadeOut: 250,
      hoverDelay: 120,
    },
  }
